packages:
  - apps/*
  - services/map
  - services/chat
  - services/board
  - services/hub
  - services/registry
  - services/fleet
  - packages/*
  - plugins/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
