export { buildApp } from "./build-app.js";
export type { FleetRepository } from "./fleet-repository.js";
export { InMemoryFleetRepository } from "./in-memory-fleet-repository.js";
export { PrismaFleetRepository } from "./prisma-fleet-repository.js";
export { fleetSchema, createFleetInputSchema } from "./types.js";
export type { Fleet, CreateFleetInput } from "./types.js";
export type { DriverRepository } from "./driver-repository.js";
export { InMemoryDriverRepository } from "./in-memory-driver-repository.js";
export { PrismaDriverRepository } from "./prisma-driver-repository.js";
export { driverSchema, createDriverInputSchema, updateDriverInputSchema } from "./types.js";
export type { Driver, CreateDriverInput, UpdateDriverInput } from "./types.js";
export type { AssetRepository, CreateAssetInput } from "./asset-repository.js";
export { InMemoryAssetRepository } from "./in-memory-asset-repository.js";
export { PrismaAssetRepository } from "./prisma-asset-repository.js";
export { VehiclePluginClient, VehiclePluginClientError } from "./vehicle-plugin-client.js";
export { assetSchema, createVehicleAssetInputSchema } from "./types.js";
export type { Asset, CreateVehicleAssetInput } from "./types.js";
export type { AssignmentRepository } from "./assignment-repository.js";
export { InMemoryAssignmentRepository } from "./in-memory-assignment-repository.js";
export { PrismaAssignmentRepository } from "./prisma-assignment-repository.js";
export { driverAssignmentSchema, assignDriverInputSchema } from "./types.js";
export type { DriverAssignment, AssignDriverInput } from "./types.js";
export type { MaintenanceSuggestionRepository, MaintenanceSuggestion } from "./maintenance-suggestion-repository.js";
export { InMemoryMaintenanceSuggestionRepository } from "./in-memory-maintenance-suggestion-repository.js";
export { PrismaMaintenanceSuggestionRepository } from "./prisma-maintenance-suggestion-repository.js";
export { SERVICE_INTERVALS_KM } from "./service-intervals.js";
